name: workspace

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name:  checkout
        uses: actions/checkout@v4.4.0
      - name: json to file
        uses: devops-actions/json-to-file@v1.0.7
